# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: kymr tech blog
email: kymr@naver.com
description: Motivation to growth & technologies !!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kymr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

repository: kakao/kakao.github.io

permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

encoding: utf-8

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

keep_files: [assets, files]

# iolo's custom
author: kymr@naver.com
image: '/files/covers/kymr.png'
asset_url: /assets
facebook:
  app_id: '100001739084793'
  username: Yongmaroo Kim
twitter:
  username: yongmaroo
google_plus:
  username: yongmaroo kim
github:
  username: kymr